require("nvim.plugins")
require("nvim.colorscheme")
require("nvim.keymaps")
require("nvim.options")
require("nvim.lsp")
require("nvim.navic")
require("nvim.telescope")
require("nvim.treesitter")
require("nvim.autopairs")
require("nvim.comment")
require("nvim.gitsigns")
require("nvim.autocommands")
require("nvim.impatient")
require("nvim.indentline")
require("nvim.whichkey")
require("nvim.dashboard")
require("nvim.nvim-tree")
require("nvim.lualine")
require("nvim.toggleterm")
require("nvim.colorizer")
require("nvim.project")
require("nvim.bookmark")
require("nvim.renamer")
require("nvim.surround")
require("nvim.notify")
require("nvim.functions")
require("nvim.ts-context")
require("nvim.registers")
require("nvim.dap")
require("nvim.lir")
require("nvim.jabs")
require("nvim.go")
require("nvim.lab")
-- require("nvim.git-worktree")
-- require("nvim.debugger")

